### ISSUE TITLE
Set Modbus address

### ISSUE THREAD

**Issue by hldiniz** [jantenhove/GoodWeLogger#11]
I am new to Arduino, please can you help? 
My Goodwe inverter has the option to Set Modbus Address. By default it is set to 247. Please can you advise if this is correct? I noticed the code sends data to 0x7F which is 127 but 247 is 0xF7.

`void GoodWeCommunicator::sendDiscovery()
{
	//send out discovery for unregistered devices.
	if(debugMode)
		Serial.println("Sending discovery");
	sendData(0x7F, 0x00, 0x00, 0x00, nullptr);
}`

**Comment by jantenhove** [comment]
The docs only mention a value of 0x7F for sending a discovery. I think it has little to do with a modbus address.
