### ISSUE TITLE
Inverter keeps trying to connect to wifi

### ISSUE THREAD

**Issue by hldiniz** [jantenhove/GoodWeLogger#13]
My inverter keeps trying to connect to the wifi. I have removed wifi module and restarted the inverted but I still can get RS485 to connect. Any tips?

**Comment by jantenhove** [comment]
Sorry for the delay. Did you fix this?
Which model inverter do you have?

**Comment by meteosat007** [comment]
Hi,

 

Yes I modified some USB code to match my inverter and all runs well now with auto restarts etc with all available measure’s sent via MQTT to be dealt with by Node Red.

 

Thanks

 

Alan

**Comment by hldiniz** [comment]
No, still the same issue. My inverter model is GW5000D-NS
