### ISSUE TITLE
RS485 converter requires a h/l signal to switch between transmit and receive

### ISSUE THREAD

**Issue by meteosat007** [jantenhove/GoodWeLogger#14]
I have the software poliing out and I have a LC-Electronics MAX485CSA TTL level RS-485 and RS-485 serial communication converter module connected but it has two pins that are et either high or low depending on whether in TX or RX mode.

Have you come across this before and can I add another data output to control the state into your code?
I have TLW1000NSU Goodwe inverter and Wifi doesnt work to portal, usb works to EZ Explorer but really want to get the local data into MQTT.

All help appreciated.

    4pin header
        DI - Driver in (the transmitter pin)
        DE - Driver enable (enabled when this pin is HIGH)
        RE - Receiver enable (enabled when this pin is LOW)
        RO - Receiver out
    4pin header
        VCC (+5VDC)
        B - Connect to pin B of the other 485 IC
        A - Connect to pin A of the other 485 IC
        GND (-)
    Screw terminal block
        B - Connect to pin B of the other 485 IC
        A - Connect to pin A of the other 485 IC

![image](https://user-images.githubusercontent.com/41062235/43045494-5e53b01a-8db1-11e8-82e7-5fcd91ecfe9f.png)

**Comment by jantenhove** [comment]
Totally missed this one, sorry.
If this is still an issue for you/others, please comment.
