### ISSUE TITLE
Daylight saving time error in PVoutput posts

### ISSUE THREAD

**Issue by bram2202** [jantenhove/GoodWeLogger#18]
After the change in DST the posts to PVoutput keeps posting the old datetime.

For example: last weekend DST ended, correct datetime for me is UTC+1.
But PVoutput receives UTC+2, and thereby show the data in the live chart 1 hour in the future.
Screenshot taken at **11:30**

![pv_output_1130](https://user-images.githubusercontent.com/6704538/47782989-e581e080-dd01-11e8-9290-d70f6b7f33d5.PNG)

Workaround probably is to reset the board, but you need to do this before/after power is generated, otherwise PVoutput wil receive multiple data for the same datetime

**Comment by jantenhove** [comment]
Time zone settings are hardcoded for now: https://github.com/jantenhove/GoodWeLogger/blob/4a638a97256bc0c7d88c07dab83a9c1134987bc2/Settings.example.h#L38
PVoutput only accepts local time instead of UTC (or any other standard).

**Comment by bram2202** [comment]
Ok, so i need to change TIMEZONE every 6 months?

**Comment by jantenhove** [comment]
Yes, or ask pvoutput to support UTC uploads. They already know the region you're in so they can convert the time more easily.

**Comment by jantenhove** [comment]
When you donate to pvoutput there is a 'Adjust Time' setting for each of your systems to correct for systems that don't support DST. See: https://pvoutput.org/help.html#live-settings-time-adj
