### ISSUE TITLE
MQTT data stays on latest value when inverter is offline

### ISSUE THREAD

**Issue by VelocityMaximus** [jantenhove/GoodWeLogger#21]
The MQTT data like vpv and vac stay on the latest value when the inverter goes offline.

It would be nice to show the real data and after a time-out the data will be zero.

Also the daily generated value should be reset at night for convenience.
Now it shows the data from the day before and resets when the inverter boots up.

**Comment by jantenhove** [comment]
I will look into this!
When the inverter goes offline, reset all variables to zero, except for eDay. The eDay will then be resetted at midnight.

**Comment by VelocityMaximus** [comment]
Latest version has a new bug: MQTT message: goodwe/96000DTUXXXXXX/online stays 1 even if the inverter went offline.

**Comment by jantenhove** [comment]
I can't see any recent change that results in that behavior. I will make a change that sends the offline message when the inverter isn't registered completely. Hopefully that will fix it.
